version: "3.8"

networks:
  default:
    driver: bridge

services:
  database:
    image: postgres:12
    env_file:
      - backend/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - default

  backend:
    build: ./backend
    entrypoint: dockerize -wait tcp://database:5432 -timeout 20s /start.sh
    environment:
      PROJECT_NAME: reconfy
      BACKEND_CORS_ORIGINS: '["http://localhost:8000", "http://localhost:3000"]'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SERVER: database
      POSTGRES_DB: app
      INITIAL_USER_NAME: User
      INITIAL_USER_EMAIL: reconfy@test.com
      INITIAL_USER_PASSWORD: reconfy
      MODEL_WEIGHTS_PATH: ../model/v4/best.pt
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - default
