version: "3.8"

services:
  rtsp-server:
    ports:
      - "1935:1935"
      - "8554:8554"
      - "8888:8888"
    environment:
      - RTSP_PROTOCOLS=tcp
    image: aler9/rtsp-simple-server

  office:
    image: linuxserver/ffmpeg:version-4.4-cli
    command: -re -stream_loop -1 -i /mnt/office.mp4 -c copy -bsf:v h264_mp4toannexb -f rtsp rtsp://rtsp-server:8554/office
    links:
      - "rtsp-server:rtsp-server"
    depends_on:
      - rtsp-server
    volumes:
      - ./backend/samples/office.mp4:/mnt/office.mp4

  electric-car:
    image: linuxserver/ffmpeg:version-4.4-cli
    command: -re -stream_loop -1 -i /mnt/electric-car.mp4 -c copy -bsf:v h264_mp4toannexb -f rtsp rtsp://rtsp-server:8554/electric-car
    links:
      - "rtsp-server:rtsp-server"
    depends_on:
      - rtsp-server
    volumes:
      - ./backend/samples/electric-car.mp4:/mnt/electric-car.mp4
